---
title: "rdsTaxVal"
format: 
  gfm:
    df_print: kable
---

```{r setup}
require(knitr)
```


## Installing the package

You may install the `rdsTaxVal` package with the following command:

```r
devtools::install_github("marbotte/rdsTaxVal")
```
## Loading the package

```{r}
library(rdsTaxVal)
```


## Reading the files 

```{r}
rdsBST<-readRDS("../data_google/4.rdsProyectos/dataRedBSTCol.rds")
rdsTDF<-readRDS("../data_google/4.rdsProyectos/dataTDF.rds")
rdsTDF$taxonomy$family<-as.character(rdsTDF$taxonomy$family)
```

## Creating the oneTable objects


```{r}
taxoBST <- new_taxo_oneTab(rdsBST$taxonomy)
taxoTDF <- new_taxo_oneTab(rdsTDF$taxonomy, "oneTable", taxonRanks_names = c(family="family", genus="genus",species="sp_epithet"), taxonRanks_epithetized = c("sp_epithet"))

taxoBST[arrayInd(which(as.matrix(taxoBST) %in% c("","N/D","NA","N/A")), .dim=dim(taxoBST), useNames = T)] <- NA
taxoTDF[arrayInd(which(as.matrix(taxoTDF) %in% c("","N/D","NA","N/A")), .dim=dim(taxoTDF), useNames = T)] <- NA


```

## Manage spaces in the taxonomy table

```{r}
suggested_spaces_BST<-checkSpace(taxoBST)
kable(suggested_spaces_BST)
taxoBST<-correct(taxoBST,suggested_spaces_BST)
```


```{r}
suggested_spaces_TDF<-checkSpace(taxoTDF)
kable(suggested_spaces_TDF)
taxoTDF<-correct(taxoTDF,suggested_spaces_TDF)
```

## Manage undetermined taxa

```{r}
suggested_undetermined_BST<-checkUndetermited(taxoBST)
kable(head(suggested_undetermined_BST))
taxoBST<-correct(taxoBST,suggested_undetermined_BST)
```

```{r}
suggested_undetermined_TDF<-checkUndetermited(taxoTDF)
kable(head(suggested_undetermined_TDF))
taxoTDF<-correct(taxoTDF,suggested_undetermined_TDF)
```


## Structural problems
### Are genera always in the same family

```{r}
suggested_unicity_familyBST<-checkUnicityRankSup(taxoBST, rank = "genus", superior="family")
kable(head(suggested_unicity_familyBST))
#correctUndetermined(taxoBST,suggested_unicity_familyBST)
taxoBST<-correct(taxoBST, suggested_unicity_familyBST)
```

```{r}
suggested_unicity_familyTDF<-checkUnicityRankSup(taxoTDF, rank="genus",superior="family")
kable(head(suggested_unicity_familyTDF))
taxoTDF<- correct(taxoTDF,suggested_unicity_familyTDF)
```

### Are taxonomic codes always associated with the same information

```{r}
suggested_taxoCodeBST <- checkUnicityCodetax(taxoBST,"takeFirst")
kable(head(showUnicityCodetax(suggested_taxoCodeBST,"suggested")))
taxoBST<-correct(taxoBST, suggested_taxoCodeBST)
```

```{r}
suggested_taxoCodeTDF <- checkUnicityCodetax(taxoTDF,"takeFirst")
kable(head(showUnicityCodetax(suggested_taxoCodeTDF,"suggested")))
taxoTDF<-correct(taxoTDF, suggested_taxoCodeTDF)
```


